debug: true

postgres:
  user: admin
  password: password123
  host: postgresql
  database: testdb
  maxConnections: 20
  metricsPort: 8082 # <-- Port dla metryk PostgreSQL

mongo:
  user: admin
  password: password123
  host: mongodb
  database: testdb
  maxConnections: 20
  metricsPort: 8081 # <-- Port dla metryk MongoDB

test:
  minClients: 1
  maxClients: 400
  stageIntervalS: 1
  requestDelayMs: 50
