debug: true

postgres:
  user: admin
  password: password123
  host: postgresql
  database: testdb
  maxConnections: 20
  metricsPort: 8082 # <-- Port dla metryk PostgreSQL

mongo:
  user: admin
  password: password123
  host: mongodb
  database: testdb
  maxConnections: 20
  metricsPort: 8081 # <-- Port dla metryk MongoDB

elasticsearch:
  host: "elasticsearch:9200"
  metricsPort: 8083

test:
  # For a sustained load test set minClients == maxClients and a longer stage interval.
  # This keeps a steady number of concurrent clients for the duration, so you can
  # observe indexes and metrics under load (the client still deletes documents
  # after each cycle; to keep documents, set delete to false in code).
  minClients: 1
  maxClients: 100
  stageIntervalS: 1
  requestDelayMs: 250
