---
debug: true
metricsPort: 8081
pgx:
  user: admin
  password: password123
  host: localhost
  database: testdb
  maxConnections: 20
mongo:
  user: admin
  password: password123
  host: localhost
  database: store
  maxConnections: 20
test:
  minClients: 1
  maxClients: 50
  stageIntervalS: 1
  requestDelayMs: 500
